name = "service"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[triggers]
crons = [ ]

[vars]
ENVIRONMENT = "production"

[[ d1_databases ]]
binding = "DATABASE"
database_name = "staging"
database_id = "96c03eb6-d7d5-40e6-8032-1cb6599ac100"

[env.staging.vars]
ENVIRONMENT = "staging"

[[ env.staging.d1_databases ]]
binding = "DATABASE"
database_name = "staging"
database_id = "96c03eb6-d7d5-40e6-8032-1cb6599ac100"
