name = "service"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[triggers]
crons = [ ]

[env.production.vars]
ENVIRONMENT = "production"

[[ env.production.d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker"

[[ env.production.r2_buckets ]]
binding = "BUCKET"
bucket_name = "staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[ env.staging.d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker-staging"

[[ env.staging.r2_buckets ]]
binding = "BUCKET"
bucket_name = "ridetracker-staging"
