name = "ridetracker-service"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[triggers]
crons = [ ]

[vars]
ENVIRONMENT = "dev"

[[migrations]]
tag = "v1"
new_classes = [ "ActivityDurableObject" ]

[[ d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker-dev"
database_id = "d61712e5-61d4-44c5-9e31-4573cdd9b3eb"

[[ r2_buckets ]]
binding = "BUCKET"
bucket_name = "ridetracker-dev"
preview_bucket_name = "ridetracker-dev"

[durable_objects]
bindings = [
    { name = "ACTIVITY_DURABLE_OBJECT", class_name = "ActivityDurableObject" }
]

[triggers]
crons = [ "0 * * * *" ]

[env.production.vars]
ENVIRONMENT = "production"

[[ env.production.d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker"
database_id = "4cb96598-71ce-47f5-b556-9ef1bfca42a1"

[[ env.production.r2_buckets ]]
binding = "BUCKET"
bucket_name = "ridetracker-production"

[env.production.durable_objects]
bindings = [
    { name = "ACTIVITY_DURABLE_OBJECT", class_name = "ActivityDurableObject" }
]

[env.production.triggers]
crons = [ "0 * * * *" ]

[env.staging.vars]
ENVIRONMENT = "staging"

[[ env.staging.d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker-staging"
database_id = "361813f2-1a83-4c3d-9df1-204fc7093b6f"

[[ env.staging.r2_buckets ]]
binding = "BUCKET"
bucket_name = "ridetracker-staging"

[env.staging.durable_objects]
bindings = [
    { name = "ACTIVITY_DURABLE_OBJECT", class_name = "ActivityDurableObject" }
]

[env.staging.triggers]
crons = [ "0 * * * *" ]
