name = "ridetracker-service"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[triggers]
crons = [ ]

[env.production.vars]
ENVIRONMENT = "production"

[[ env.production.d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker"
database_id = "4cb96598-71ce-47f5-b556-9ef1bfca42a1"

[[ env.production.r2_buckets ]]
binding = "BUCKET"
bucket_name = "staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[ env.staging.d1_databases ]]
binding = "DATABASE"
database_name = "ridetracker-staging"
database_id = "161d4088-c809-4ea3-b10b-412e9ddc7506"

[[ env.staging.r2_buckets ]]
binding = "BUCKET"
bucket_name = "ridetracker-staging"
