run-name: Create backup

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Create Turso backup
    runs-on: ubuntu-latest
    env:
      TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
    steps:
      - name: Install Turso CLI
        run: brew install tursodatabase/tap/turso

      - name: Create temporary folder
        run: mkdir ${{ runner.temp }}/artifacts
      
      - name: Dump ridetracker-production
        run: turso db shell ridetracker-production .dump > ${{ runner.temp }}/artifacts/database.sql
      
      - name: Get current timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - uses: actions/upload-artifact@v3
        with:
          name: ridetracker-production-turso-${{ env.TIMESTAMP }}
          path: ${{ runner.temp }}/artifacts
