run-name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to staging
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: staging
      