run-name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ridetracker'

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - run: npm ci
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Publish using wrangler
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_WORKERS_TOKEN }}
          command: publish --env staging --var GITHUB_SHA:${{ github.sha }} CLOUDFLARE_ACCOUNT_ID:${{ secrets.CLOUDFLARE_ACCOUNT_ID }} CLOUDFLARE_API_IMAGES_TOKEN:${{ secrets.CLOUDFLARE_API_IMAGES_TOKEN }} GOOGLE_MAPS_API_TOKEN:${{ secrets.GOOGLE_MAPS_API_TOKEN }}
