run-name: Deploy to production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to production
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
      