run-name: Create backup

on:
  workflow_dispatch:
    inputs:
      database:
        type: "string"
        required: true
        
  workflow_call:
    inputs:
      database:
        type: "string"
        required: true

jobs:
  deploy:
    name: Create Turso backup
    runs-on: ubuntu-latest
    env:
      TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
    steps:
      - name: Create temporary folder
        run: mkdir ${{ runner.temp }}/artifacts
        
      - name: Install Turso CLI
        run: curl -sSfL https://get.tur.so/install.sh | bash
        continue-on-error: true
      
      - name: Dump ${{ inputs.database }}
        run: /home/runner/.turso/turso db shell ${{ inputs.database }} .dump > ${{ runner.temp }}/artifacts/database.sql
      
      - name: Get current timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      
      - uses: actions/upload-artifact@v3
        with:
          name: turso-${{ inputs.database }}-${{ env.TIMESTAMP }}
          path: ${{ runner.temp }}/artifacts
