run-name: Deploy to staging and run tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to staging and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install
        
      - name: Publish using wrangler
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_WORKERS_TOKEN }}
          command: publish --env staging --var GITHUB_SHA:${{ github.sha }} CLOUDFLARE_ACCOUNT_ID:${{ secrets.CLOUDFLARE_ACCOUNT_ID }} CLOUDFLARE_API_IMAGES_TOKEN:${{ secrets.CLOUDFLARE_API_IMAGES_TOKEN }} GOOGLE_MAPS_API_TOKEN:${{ secrets.GOOGLE_MAPS_API_TOKEN }}
        
      - name: Run vite tests
        env:
          VITE_GITHUB_SHA: ${{ github.sha }}
          VITE_GOOGLE_MAPS_API_TOKEN: ${{ secrets.GOOGLE_MAPS_API_TOKEN }}
        run: npx vitest run
