run-name: Run tests by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install
        
      - name: Publish using wrangler
        run: npx wrangler publish --env staging
        
      - name: Upload empty database
        run: wrangler d1 execute staging --file ./schema.sql --env staging
        
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install
        
      - name: Run vite tests
        run: vitest run
        
