name: Upload avatars to Cloudflare Images and API

on: workflow_dispatch

jobs:
  upload_avatars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Upload avatars
        id: upload_avatars
        run: |
          for dir in ./assets/avatars/*/; do
            dirname=$(basename "$dir")
            echo "Processing avatars in $dirname folder"
            files=$(find "$dir" -type f -name "*.png")
            for file in $files; do
              echo "Processing file: $file"
              response=$(curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/images/v1" \
                -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_IMAGES_TOKEN }}" \
                -H "Content-Type: image/png" \
                -H "X-Content-Type: image/png" \
                --data-binary "@$file" \
                --silent)
              id=$(echo "$response" | jq -r '.result.id')
              echo "Image uploaded with ID: $id"
              echo "::set-output name=ids::$id"
            done
          done
