name: Upload avatars to Cloudflare Images and API

on: workflow_dispatch

jobs:
  upload_avatars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Install dependencies
      run: npm install
      
    - name: List PNG files in avatars folder
      run: |
        echo "$(find ./assets/avatars -name '*.png' -type f)" > png_files.txt
      id: list-files
      
    - name: Get Direct Creator Upload URL from Cloudflare Images
      run: |
        upload_urls=""
        while read file; do
          filename=$(basename "$file")
          response=$(curl -s -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/images/v1/direct_upload" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_IMAGES_TOKEN }}" \
            -H "Content-Type: image/png" \
            -d '{"filename":"'"$filename"'", "metadata":{"type":"avatar"}}')
          upload_url=$(echo "$response" | jq -r '.upload_url')
          upload_urls="$upload_urls $upload_url $filename"
        done < png_files.txt
        echo "UPLOAD_URLS=$upload_urls" >> $GITHUB_ENV
      id: upload-urls
      
    - name: Upload images to Cloudflare Images
      run: |
        uploads=""
        while read url; do
          upload_url=$(echo "$url" | cut -d' ' -f2)
          filename=$(echo "$url" | cut -d' ' -f3-)
          curl -X PUT --data-binary "@./avatars/$filename" "$upload_url"
          uploads="$uploads $filename"
        done <<< "$UPLOAD_URLS"
        echo "UPLOADS=$uploads" >> $GITHUB_ENV
      id: uploads
      
    - name: Call API endpoint
      run: |
        while read upload; do
          filename=$upload
          type=$(basename $(dirname ./avatars/$filename))
          image_id=$(curl -s -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_IMAGES_TOKEN }}" "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/images/v1?filename=$filename" | jq -r '.result[0].id')
          curl -X POST -d '{"image_id":"'$image_id'", "type":"'$type'", "filename":"'$filename'"}' -H 'Content-Type: application/json' https://example.com/api/avatars/upload
        done <<< "$UPLOADS"
