name: Upload avatars to Cloudflare Images and API

on: workflow_dispatch

jobs:
  upload_avatars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Upload avatars
        id: upload_avatars
        run: |
          for dir in ./assets/avatars/*/; do
            dir_name=$(basename $dir)
            for file in $dir*.png; do
              file_name=$(basename "$file")
              response=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_IMAGES_TOKEN }}" \
                "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/media" \
                -d "meta[type]=avatar" \
                --upload-file "$file")
              image_id=$(echo $response | jq -r .result.id)
              echo "::set-output name=${file_name%.*}::$image_id"
              echo "::set-output name=${file_name%.*}_type::$dir_name"
            done
          done
          